/*
 * generated by Xtext 2.24.0
 */
package edu.upb.lp.isc.validation;

import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.xtext.validation.Check;

import edu.upb.lp.isc.miVersion.Aritmetica;
import edu.upb.lp.isc.miVersion.Bloque;
import edu.upb.lp.isc.miVersion.Declaraciones;
import edu.upb.lp.isc.miVersion.FuncionSimplificada;
import edu.upb.lp.isc.miVersion.If;
import edu.upb.lp.isc.miVersion.List;
import edu.upb.lp.isc.miVersion.ListContent;
import edu.upb.lp.isc.miVersion.MiVersionPackage;
import edu.upb.lp.isc.miVersion.Programa;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MiVersionValidator extends AbstractMiVersionValidator {
	
	public static final String INVALID_NAME = "mal";
	public static final EStructuralFeature F = null;


//.matches("[0-9]*"
	@Check
	public void checkAritmeticaDosIntsEQR(Aritmetica aritmetica) {
		if ( aritmetica.getOp().getOp().equals("expt")
				|| aritmetica.getOp().getOp().equals("remainder") || aritmetica.getOp().getOp().equals("quotient") 
				|| aritmetica.getOp().getOp().equals("+") || aritmetica.getOp().getOp().equals("-")
				|| aritmetica.getOp().getOp().equals("*") || aritmetica.getOp().getOp().equals("/") ) {
			if (!(aritmetica.getArgument().get(0).getClass().getSimpleName().equals("MyIntImpl") || aritmetica.getArgument().get(0).getClass().getSimpleName().equals("AritmeticaImpl")
					|| aritmetica.getArgument().get(0).getClass().getSimpleName().equals("VariableImpl") || aritmetica.getArgument().get(0).getClass().getSimpleName().equals("LlamarFuncionImpl"))) {
				error("expt, quotient y remainder son (op Int Int)"+ aritmetica.getArgument().get(0).getClass().getSimpleName(), MiVersionPackage.Literals.ARITMETICA__ARGUMENT,
						INVALID_NAME);
			}else if (!(aritmetica.getArgument().get(1).getClass().getSimpleName().equals("MyIntImpl") || aritmetica.getArgument().get(1).getClass().getSimpleName().equals("AritmeticaImpl" )
					|| aritmetica.getArgument().get(1).getClass().getSimpleName().equals("VariableImpl" )|| aritmetica.getArgument().get(1).getClass().getSimpleName().equals("LlamarFuncionImpl")
					)) {//|| aritmetica.getArgument().get(1).getClass().getSimpleName().equals("VariableImpl")
				error("expt, quotient y remainder son (op Int Int)"+ aritmetica.getArgument().get(1).getClass().getSimpleName(), MiVersionPackage.Literals.ARITMETICA__ARGUMENT,
						INVALID_NAME);
			}
		}
	}
	//AritmeticaImpl
	@Check
	public void checkListaAny(List lista) {
		for (ListContent nose: lista.getDatal()) {
			if(!(nose.getClass().getSimpleName().equals("VariableImpl") || nose.getClass().getSimpleName().equals("LlamarFuncionImpl"))) {
		for (ListContent variable: lista.getDatal()) {
			String auxi=lista.getDatal().get(0).getClass().getSimpleName();
			if (!(variable.getClass().getSimpleName().equals(auxi))) {
				error("no (List Any)", MiVersionPackage.Literals.LIST__DATAL,
						INVALID_NAME);
			}
		}
			}
		}
	}
//	@Check
//	public void checkIncongrucion(Aritmetica aritmetica) {
//		if (aritmetica.getOp().toString() == "/") {
//			if (aritmetica.getArgument().get(0).toString() == "0" && aritmetica.getArgument().get(1).toString() == "0") {
//				error("expt, quotient y remainder son (op Int Int)", MiVersionPackage.Literals.ARITMETICA__ARGUMENT,
//						INVALID_NAME);
//			}
//		}
//	}
	@Check
	public void checkTamanio(Aritmetica aritmetica) { //{'<' | '>=' | '>' | '<=' | '!='
		if (aritmetica.getOp().getOp().equals("/") || aritmetica.getOp().getOp().equals("*") || aritmetica.getOp().getOp().equals("expt")
				|| aritmetica.getOp().getOp().equals("remainder") || aritmetica.getOp().getOp().equals("quotient") || aritmetica.getOp().getOp().equals("<") 
				|| aritmetica.getOp().getOp().equals(">=") || aritmetica.getOp().getOp().equals(">") || aritmetica.getOp().getOp().equals("<=") ||
				aritmetica.getOp().getOp().equals("!=") || aritmetica.getOp().getOp().equals("==")){
				//	|| aritmetsica.getOp().toString() == "remainder") {
			if (aritmetica.getArgument().size() > 2) {
				error("(op data1 data2) no mas de dos datas", MiVersionPackage.Literals.ARITMETICA__ARGUMENT,
						INVALID_NAME);
			}
		}
	}
	
	@Check
	public void checkDataSuelta(Programa prog) {
		for (Declaraciones variable: prog.getDeclaraciones() ){
			if (variable.getClass().getSimpleName().equals("MyIntImpl") || variable.getClass().getSimpleName().equals("MyStringImpl") ||
					variable.getClass().getSimpleName().equals("ListImpl") || variable.getClass().getSimpleName().equals("BoolImpl")||
					variable.getClass().getSimpleName().equals("VariableImpl")  ) {
				error("not only cons", MiVersionPackage.Literals.DECLARACIONES,
						F);
			}
		}
	}
	
	@Check
	public void checkDataSueltaBloque(If fi) {
		//for (Bloque variable: iiif.getThen() ){
		for (Bloque variable: fi.getThen() ){
			if (variable.getClass().getSimpleName().equals("MyIntImpl") || variable.getClass().getSimpleName().equals("MyStringImpl") ||
					variable.getClass().getSimpleName().equals("ListImpl") || variable.getClass().getSimpleName().equals("BoolImpl")||
					variable.getClass().getSimpleName().equals("VariableImpl")) {
				error("not only cons", MiVersionPackage.Literals.DECLARACIONES,
						F);
			}
		}
	
			 		
		
		if(fi.getEelse().size() > 0) {
		for (Bloque variable: fi.getEelse() ){
			if (variable.getClass().getSimpleName().equals("MyIntImpl") || variable.getClass().getSimpleName().equals("MyStringImpl") ||
					variable.getClass().getSimpleName().equals("ListImpl") || variable.getClass().getSimpleName().equals("BoolImpl")||
					variable.getClass().getSimpleName().equals("VariableImpl")) {
				error("not only cons", MiVersionPackage.Literals.IF__EELSE,
						INVALID_NAME);
			}
		}
		}
		
	}


	@Check
	public void checkBLoqueFun(FuncionSimplificada isNotFun) {
		//for (Bloque variable: iiif.getThen() ){
		if(isNotFun.getThen().size() > 0) {
		for (Bloque variable: isNotFun.getThen() ){
			if (variable.getClass().getSimpleName().equals("MyIntImpl") || variable.getClass().getSimpleName().equals("MyStringImpl") ||
					variable.getClass().getSimpleName().equals("ListImpl") || variable.getClass().getSimpleName().equals("BoolImpl")||
					variable.getClass().getSimpleName().equals("VariableImpl")) {
				error("not only cons", MiVersionPackage.Literals.FUNCION_SIMPLIFICADA__THEN,
						INVALID_NAME);
			}
		}
		}
	}
	
//	@Check
//	public void checkAtributisFun(LlamarFuncion llam, FuncionSimplificada notFun) {
//		//for (Bloque variable: iiif.getThen() ){
//		int aux = 0;
//		for (Argument variable: notFun.getParameter()) {
//			if(variable.getClass().getSimpleName().equals(llam.getArguments().get(aux).getClass().getSimpleName()))
//		error("not only cons", MiVersionPackage.Literals.LLAMAR_FUNCION__NOMBRE_FUNCION,
//					INVALID_NAME);
//			
//		}
//		
//
//	}
	



//TODO lo de aritmetica check
//TODO lo de aritmetica check no mas de 2
// TODO LISTAS no LIST any check
// TODO llamados de funciones con el mismo tamanio
// TODO llamados de funciones con el mismo tipo de dato
// TODO incongruencias matematicas decartado

//Variables con el mismo tipo de dato??
	




}
