/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.upb.lp.isc.CompilacionRuntimeModule;
import edu.upb.lp.isc.CompilacionStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CompilacionIdeSetup extends CompilacionStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CompilacionRuntimeModule(), new CompilacionIdeModule()));
	}
	
}
