/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class CompilacionValidator extends AbstractCompilacionValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					CompilacionPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
//TODO lo de aritmetica
// TODO LISTAS no LIST any
	
	
}
