/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.Aritmetica#getOp <em>Op</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.Aritmetica#getArgument <em>Argument</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getAritmetica()
 * @model
 * @generated
 */
public interface Aritmetica extends Expr
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference.
   * @see #setOp(Operadores)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getAritmetica_Op()
   * @model containment="true"
   * @generated
   */
  Operadores getOp();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.Aritmetica#getOp <em>Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' containment reference.
   * @see #getOp()
   * @generated
   */
  void setOp(Operadores value);

  /**
   * Returns the value of the '<em><b>Argument</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.compilacion.MyInt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument</em>' containment reference list.
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getAritmetica_Argument()
   * @model containment="true"
   * @generated
   */
  EList<MyInt> getArgument();

} // Aritmetica
