/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atributo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.Atributo#getAtributoName <em>Atributo Name</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getAtributo()
 * @model
 * @generated
 */
public interface Atributo extends EObject
{
  /**
   * Returns the value of the '<em><b>Atributo Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atributo Name</em>' attribute.
   * @see #setAtributoName(String)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getAtributo_AtributoName()
   * @model
   * @generated
   */
  String getAtributoName();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.Atributo#getAtributoName <em>Atributo Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atributo Name</em>' attribute.
   * @see #getAtributoName()
   * @generated
   */
  void setAtributoName(String value);

} // Atributo
