/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.isc.compilacion.CompilacionFactory
 * @model kind="package"
 * @generated
 */
public interface CompilacionPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "compilacion";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/isc/Compilacion";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "compilacion";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CompilacionPackage eINSTANCE = edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.ProgramaImpl <em>Programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.ProgramaImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getPrograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__NAME = 0;

  /**
   * The feature id for the '<em><b>Declaraciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__DECLARACIONES = 1;

  /**
   * The feature id for the '<em><b>Ejecuciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__EJECUCIONES = 2;

  /**
   * The number of structural features of the '<em>Programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.EjecucionImpl <em>Ejecucion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.EjecucionImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getEjecucion()
   * @generated
   */
  int EJECUCION = 1;

  /**
   * The number of structural features of the '<em>Ejecucion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EJECUCION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.DeclaracionesImpl <em>Declaraciones</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.DeclaracionesImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getDeclaraciones()
   * @generated
   */
  int DECLARACIONES = 2;

  /**
   * The number of structural features of the '<em>Declaraciones</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACIONES_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.SimpleImpl <em>Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.SimpleImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getSimple()
   * @generated
   */
  int SIMPLE = 3;

  /**
   * The number of structural features of the '<em>Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FEATURE_COUNT = DECLARACIONES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.ImprimibleImpl <em>Imprimible</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.ImprimibleImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getImprimible()
   * @generated
   */
  int IMPRIMIBLE = 4;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPRIMIBLE__VAR = 0;

  /**
   * The feature id for the '<em><b>Fun</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPRIMIBLE__FUN = 1;

  /**
   * The number of structural features of the '<em>Imprimible</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPRIMIBLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.NoImprimibleImpl <em>No Imprimible</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.NoImprimibleImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getNoImprimible()
   * @generated
   */
  int NO_IMPRIMIBLE = 5;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NO_IMPRIMIBLE__VAR = 0;

  /**
   * The feature id for the '<em><b>Fun</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NO_IMPRIMIBLE__FUN = 1;

  /**
   * The number of structural features of the '<em>No Imprimible</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NO_IMPRIMIBLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.ExprImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 6;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = EJECUCION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.DataType_Impl <em>Data Type </em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.DataType_Impl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getDataType_()
   * @generated
   */
  int DATA_TYPE_ = 7;

  /**
   * The number of structural features of the '<em>Data Type </em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__FEATURE_COUNT = EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.MyIntImpl <em>My Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.MyIntImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getMyInt()
   * @generated
   */
  int MY_INT = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_INT__VALUE = DATA_TYPE__FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>My Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_INT_FEATURE_COUNT = DATA_TYPE__FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.MyStringImpl <em>My String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.MyStringImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getMyString()
   * @generated
   */
  int MY_STRING = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_STRING__VALUE = DATA_TYPE__FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>My String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_STRING_FEATURE_COUNT = DATA_TYPE__FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.MyBoolImpl <em>My Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.MyBoolImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getMyBool()
   * @generated
   */
  int MY_BOOL = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_BOOL__VALUE = DATA_TYPE__FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>My Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_BOOL_FEATURE_COUNT = DATA_TYPE__FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.IsDataTypeImpl <em>Is Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.IsDataTypeImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getIsDataType()
   * @generated
   */
  int IS_DATA_TYPE = 11;

  /**
   * The feature id for the '<em><b>Is Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_DATA_TYPE__IS_TYPE = 0;

  /**
   * The number of structural features of the '<em>Is Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_DATA_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.AritmeticaImpl <em>Aritmetica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.AritmeticaImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getAritmetica()
   * @generated
   */
  int ARITMETICA = 12;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITMETICA__OP = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Argument</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITMETICA__ARGUMENT = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Aritmetica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITMETICA_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.OperadoresImpl <em>Operadores</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.OperadoresImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getOperadores()
   * @generated
   */
  int OPERADORES = 13;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERADORES__OP = 0;

  /**
   * The number of structural features of the '<em>Operadores</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERADORES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.VariablesImpl <em>Variables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.VariablesImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getVariables()
   * @generated
   */
  int VARIABLES = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES__NAME = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES__VAL = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.EqualImpl <em>Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.EqualImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getEqual()
   * @generated
   */
  int EQUAL = 22;

  /**
   * The feature id for the '<em><b>N1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__N1 = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>N2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL__N2 = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.Boolean_OpImpl <em>Boolean Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.Boolean_OpImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getBoolean_Op()
   * @generated
   */
  int BOOLEAN_OP = 15;

  /**
   * The feature id for the '<em><b>N1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OP__N1 = EQUAL__N1;

  /**
   * The feature id for the '<em><b>N2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OP__N2 = EQUAL__N2;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OP__OP = EQUAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_OP_FEATURE_COUNT = EQUAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.BoolImpl <em>Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.BoolImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getBool()
   * @generated
   */
  int BOOL = 16;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL__OP = 0;

  /**
   * The number of structural features of the '<em>Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.EstructurasImpl <em>Estructuras</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.EstructurasImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getEstructuras()
   * @generated
   */
  int ESTRUCTURAS = 17;

  /**
   * The number of structural features of the '<em>Estructuras</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRUCTURAS_FEATURE_COUNT = SIMPLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.ListImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getList()
   * @generated
   */
  int LIST = 18;

  /**
   * The feature id for the '<em><b>Type Of List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__TYPE_OF_LIST = DATA_TYPE__FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = DATA_TYPE__FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.LargoListaImpl <em>Largo Lista</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.LargoListaImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getLargoLista()
   * @generated
   */
  int LARGO_LISTA = 19;

  /**
   * The number of structural features of the '<em>Largo Lista</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LARGO_LISTA_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.AtributoImpl <em>Atributo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.AtributoImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getAtributo()
   * @generated
   */
  int ATRIBUTO = 20;

  /**
   * The feature id for the '<em><b>Atributo Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO__ATRIBUTO_NAME = 0;

  /**
   * The number of structural features of the '<em>Atributo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.FuncionSimplificadaImpl <em>Funcion Simplificada</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.FuncionSimplificadaImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getFuncionSimplificada()
   * @generated
   */
  int FUNCION_SIMPLIFICADA = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION_SIMPLIFICADA__NAME = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Atributo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION_SIMPLIFICADA__ATRIBUTO = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION_SIMPLIFICADA__THEN = EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Funcion Simplificada</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION_SIMPLIFICADA_FEATURE_COUNT = EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.IfImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getIf()
   * @generated
   */
  int IF = 23;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__CONDITION = ESTRUCTURAS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__THEN = ESTRUCTURAS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__ELSE = ESTRUCTURAS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = ESTRUCTURAS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.isc.compilacion.impl.BloqueImpl <em>Bloque</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.isc.compilacion.impl.BloqueImpl
   * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getBloque()
   * @generated
   */
  int BLOQUE = 24;

  /**
   * The number of structural features of the '<em>Bloque</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOQUE_FEATURE_COUNT = 0;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programa</em>'.
   * @see edu.upb.lp.isc.compilacion.Programa
   * @generated
   */
  EClass getPrograma();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.Programa#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.compilacion.Programa#getName()
   * @see #getPrograma()
   * @generated
   */
  EAttribute getPrograma_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.compilacion.Programa#getDeclaraciones <em>Declaraciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declaraciones</em>'.
   * @see edu.upb.lp.isc.compilacion.Programa#getDeclaraciones()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Declaraciones();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.compilacion.Programa#getEjecuciones <em>Ejecuciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ejecuciones</em>'.
   * @see edu.upb.lp.isc.compilacion.Programa#getEjecuciones()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Ejecuciones();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Ejecucion <em>Ejecucion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ejecucion</em>'.
   * @see edu.upb.lp.isc.compilacion.Ejecucion
   * @generated
   */
  EClass getEjecucion();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Declaraciones <em>Declaraciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaraciones</em>'.
   * @see edu.upb.lp.isc.compilacion.Declaraciones
   * @generated
   */
  EClass getDeclaraciones();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Simple <em>Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple</em>'.
   * @see edu.upb.lp.isc.compilacion.Simple
   * @generated
   */
  EClass getSimple();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Imprimible <em>Imprimible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Imprimible</em>'.
   * @see edu.upb.lp.isc.compilacion.Imprimible
   * @generated
   */
  EClass getImprimible();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.compilacion.Imprimible#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see edu.upb.lp.isc.compilacion.Imprimible#getVar()
   * @see #getImprimible()
   * @generated
   */
  EReference getImprimible_Var();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.compilacion.Imprimible#getFun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Fun</em>'.
   * @see edu.upb.lp.isc.compilacion.Imprimible#getFun()
   * @see #getImprimible()
   * @generated
   */
  EReference getImprimible_Fun();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.NoImprimible <em>No Imprimible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>No Imprimible</em>'.
   * @see edu.upb.lp.isc.compilacion.NoImprimible
   * @generated
   */
  EClass getNoImprimible();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.compilacion.NoImprimible#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see edu.upb.lp.isc.compilacion.NoImprimible#getVar()
   * @see #getNoImprimible()
   * @generated
   */
  EReference getNoImprimible_Var();

  /**
   * Returns the meta object for the reference '{@link edu.upb.lp.isc.compilacion.NoImprimible#getFun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Fun</em>'.
   * @see edu.upb.lp.isc.compilacion.NoImprimible#getFun()
   * @see #getNoImprimible()
   * @generated
   */
  EReference getNoImprimible_Fun();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see edu.upb.lp.isc.compilacion.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.DataType_ <em>Data Type </em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type </em>'.
   * @see edu.upb.lp.isc.compilacion.DataType_
   * @generated
   */
  EClass getDataType_();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.MyInt <em>My Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My Int</em>'.
   * @see edu.upb.lp.isc.compilacion.MyInt
   * @generated
   */
  EClass getMyInt();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.MyInt#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.compilacion.MyInt#getValue()
   * @see #getMyInt()
   * @generated
   */
  EAttribute getMyInt_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.MyString <em>My String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My String</em>'.
   * @see edu.upb.lp.isc.compilacion.MyString
   * @generated
   */
  EClass getMyString();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.MyString#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.isc.compilacion.MyString#getValue()
   * @see #getMyString()
   * @generated
   */
  EAttribute getMyString_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.MyBool <em>My Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My Bool</em>'.
   * @see edu.upb.lp.isc.compilacion.MyBool
   * @generated
   */
  EClass getMyBool();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.MyBool#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see edu.upb.lp.isc.compilacion.MyBool#getValue()
   * @see #getMyBool()
   * @generated
   */
  EReference getMyBool_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.IsDataType <em>Is Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Is Data Type</em>'.
   * @see edu.upb.lp.isc.compilacion.IsDataType
   * @generated
   */
  EClass getIsDataType();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.IsDataType#getIsType <em>Is Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Is Type</em>'.
   * @see edu.upb.lp.isc.compilacion.IsDataType#getIsType()
   * @see #getIsDataType()
   * @generated
   */
  EReference getIsDataType_IsType();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Aritmetica <em>Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aritmetica</em>'.
   * @see edu.upb.lp.isc.compilacion.Aritmetica
   * @generated
   */
  EClass getAritmetica();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.Aritmetica#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see edu.upb.lp.isc.compilacion.Aritmetica#getOp()
   * @see #getAritmetica()
   * @generated
   */
  EReference getAritmetica_Op();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.compilacion.Aritmetica#getArgument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Argument</em>'.
   * @see edu.upb.lp.isc.compilacion.Aritmetica#getArgument()
   * @see #getAritmetica()
   * @generated
   */
  EReference getAritmetica_Argument();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Operadores <em>Operadores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operadores</em>'.
   * @see edu.upb.lp.isc.compilacion.Operadores
   * @generated
   */
  EClass getOperadores();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.Operadores#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.compilacion.Operadores#getOp()
   * @see #getOperadores()
   * @generated
   */
  EAttribute getOperadores_Op();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Variables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variables</em>'.
   * @see edu.upb.lp.isc.compilacion.Variables
   * @generated
   */
  EClass getVariables();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.Variables#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.compilacion.Variables#getName()
   * @see #getVariables()
   * @generated
   */
  EAttribute getVariables_Name();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.Variables#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see edu.upb.lp.isc.compilacion.Variables#getVal()
   * @see #getVariables()
   * @generated
   */
  EReference getVariables_Val();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Boolean_Op <em>Boolean Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Op</em>'.
   * @see edu.upb.lp.isc.compilacion.Boolean_Op
   * @generated
   */
  EClass getBoolean_Op();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.Boolean_Op#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.compilacion.Boolean_Op#getOp()
   * @see #getBoolean_Op()
   * @generated
   */
  EAttribute getBoolean_Op_Op();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool</em>'.
   * @see edu.upb.lp.isc.compilacion.Bool
   * @generated
   */
  EClass getBool();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.Bool#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.upb.lp.isc.compilacion.Bool#getOp()
   * @see #getBool()
   * @generated
   */
  EAttribute getBool_Op();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Estructuras <em>Estructuras</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Estructuras</em>'.
   * @see edu.upb.lp.isc.compilacion.Estructuras
   * @generated
   */
  EClass getEstructuras();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see edu.upb.lp.isc.compilacion.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.compilacion.List#getTypeOfList <em>Type Of List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type Of List</em>'.
   * @see edu.upb.lp.isc.compilacion.List#getTypeOfList()
   * @see #getList()
   * @generated
   */
  EReference getList_TypeOfList();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.LargoLista <em>Largo Lista</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Largo Lista</em>'.
   * @see edu.upb.lp.isc.compilacion.LargoLista
   * @generated
   */
  EClass getLargoLista();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Atributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atributo</em>'.
   * @see edu.upb.lp.isc.compilacion.Atributo
   * @generated
   */
  EClass getAtributo();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.Atributo#getAtributoName <em>Atributo Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Atributo Name</em>'.
   * @see edu.upb.lp.isc.compilacion.Atributo#getAtributoName()
   * @see #getAtributo()
   * @generated
   */
  EAttribute getAtributo_AtributoName();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.FuncionSimplificada <em>Funcion Simplificada</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Funcion Simplificada</em>'.
   * @see edu.upb.lp.isc.compilacion.FuncionSimplificada
   * @generated
   */
  EClass getFuncionSimplificada();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.isc.compilacion.FuncionSimplificada#getName()
   * @see #getFuncionSimplificada()
   * @generated
   */
  EAttribute getFuncionSimplificada_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getAtributo <em>Atributo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atributo</em>'.
   * @see edu.upb.lp.isc.compilacion.FuncionSimplificada#getAtributo()
   * @see #getFuncionSimplificada()
   * @generated
   */
  EReference getFuncionSimplificada_Atributo();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see edu.upb.lp.isc.compilacion.FuncionSimplificada#getThen()
   * @see #getFuncionSimplificada()
   * @generated
   */
  EReference getFuncionSimplificada_Then();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Equal <em>Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal</em>'.
   * @see edu.upb.lp.isc.compilacion.Equal
   * @generated
   */
  EClass getEqual();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.Equal#getN1 <em>N1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>N1</em>'.
   * @see edu.upb.lp.isc.compilacion.Equal#getN1()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_N1();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.Equal#getN2 <em>N2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>N2</em>'.
   * @see edu.upb.lp.isc.compilacion.Equal#getN2()
   * @see #getEqual()
   * @generated
   */
  EReference getEqual_N2();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see edu.upb.lp.isc.compilacion.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.If#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see edu.upb.lp.isc.compilacion.If#getCondition()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Condition();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.If#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then</em>'.
   * @see edu.upb.lp.isc.compilacion.If#getThen()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Then();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.isc.compilacion.If#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else</em>'.
   * @see edu.upb.lp.isc.compilacion.If#getElse()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Else();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.isc.compilacion.Bloque <em>Bloque</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bloque</em>'.
   * @see edu.upb.lp.isc.compilacion.Bloque
   * @generated
   */
  EClass getBloque();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CompilacionFactory getCompilacionFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.ProgramaImpl <em>Programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.ProgramaImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getPrograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getPrograma();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAMA__NAME = eINSTANCE.getPrograma_Name();

    /**
     * The meta object literal for the '<em><b>Declaraciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__DECLARACIONES = eINSTANCE.getPrograma_Declaraciones();

    /**
     * The meta object literal for the '<em><b>Ejecuciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__EJECUCIONES = eINSTANCE.getPrograma_Ejecuciones();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.EjecucionImpl <em>Ejecucion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.EjecucionImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getEjecucion()
     * @generated
     */
    EClass EJECUCION = eINSTANCE.getEjecucion();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.DeclaracionesImpl <em>Declaraciones</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.DeclaracionesImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getDeclaraciones()
     * @generated
     */
    EClass DECLARACIONES = eINSTANCE.getDeclaraciones();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.SimpleImpl <em>Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.SimpleImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getSimple()
     * @generated
     */
    EClass SIMPLE = eINSTANCE.getSimple();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.ImprimibleImpl <em>Imprimible</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.ImprimibleImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getImprimible()
     * @generated
     */
    EClass IMPRIMIBLE = eINSTANCE.getImprimible();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPRIMIBLE__VAR = eINSTANCE.getImprimible_Var();

    /**
     * The meta object literal for the '<em><b>Fun</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPRIMIBLE__FUN = eINSTANCE.getImprimible_Fun();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.NoImprimibleImpl <em>No Imprimible</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.NoImprimibleImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getNoImprimible()
     * @generated
     */
    EClass NO_IMPRIMIBLE = eINSTANCE.getNoImprimible();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NO_IMPRIMIBLE__VAR = eINSTANCE.getNoImprimible_Var();

    /**
     * The meta object literal for the '<em><b>Fun</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NO_IMPRIMIBLE__FUN = eINSTANCE.getNoImprimible_Fun();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.ExprImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.DataType_Impl <em>Data Type </em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.DataType_Impl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getDataType_()
     * @generated
     */
    EClass DATA_TYPE_ = eINSTANCE.getDataType_();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.MyIntImpl <em>My Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.MyIntImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getMyInt()
     * @generated
     */
    EClass MY_INT = eINSTANCE.getMyInt();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MY_INT__VALUE = eINSTANCE.getMyInt_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.MyStringImpl <em>My String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.MyStringImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getMyString()
     * @generated
     */
    EClass MY_STRING = eINSTANCE.getMyString();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MY_STRING__VALUE = eINSTANCE.getMyString_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.MyBoolImpl <em>My Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.MyBoolImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getMyBool()
     * @generated
     */
    EClass MY_BOOL = eINSTANCE.getMyBool();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_BOOL__VALUE = eINSTANCE.getMyBool_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.IsDataTypeImpl <em>Is Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.IsDataTypeImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getIsDataType()
     * @generated
     */
    EClass IS_DATA_TYPE = eINSTANCE.getIsDataType();

    /**
     * The meta object literal for the '<em><b>Is Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_DATA_TYPE__IS_TYPE = eINSTANCE.getIsDataType_IsType();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.AritmeticaImpl <em>Aritmetica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.AritmeticaImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getAritmetica()
     * @generated
     */
    EClass ARITMETICA = eINSTANCE.getAritmetica();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITMETICA__OP = eINSTANCE.getAritmetica_Op();

    /**
     * The meta object literal for the '<em><b>Argument</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITMETICA__ARGUMENT = eINSTANCE.getAritmetica_Argument();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.OperadoresImpl <em>Operadores</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.OperadoresImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getOperadores()
     * @generated
     */
    EClass OPERADORES = eINSTANCE.getOperadores();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERADORES__OP = eINSTANCE.getOperadores_Op();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.VariablesImpl <em>Variables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.VariablesImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getVariables()
     * @generated
     */
    EClass VARIABLES = eINSTANCE.getVariables();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLES__NAME = eINSTANCE.getVariables_Name();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLES__VAL = eINSTANCE.getVariables_Val();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.Boolean_OpImpl <em>Boolean Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.Boolean_OpImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getBoolean_Op()
     * @generated
     */
    EClass BOOLEAN_OP = eINSTANCE.getBoolean_Op();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_OP__OP = eINSTANCE.getBoolean_Op_Op();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.BoolImpl <em>Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.BoolImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getBool()
     * @generated
     */
    EClass BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL__OP = eINSTANCE.getBool_Op();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.EstructurasImpl <em>Estructuras</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.EstructurasImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getEstructuras()
     * @generated
     */
    EClass ESTRUCTURAS = eINSTANCE.getEstructuras();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.ListImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>Type Of List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__TYPE_OF_LIST = eINSTANCE.getList_TypeOfList();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.LargoListaImpl <em>Largo Lista</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.LargoListaImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getLargoLista()
     * @generated
     */
    EClass LARGO_LISTA = eINSTANCE.getLargoLista();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.AtributoImpl <em>Atributo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.AtributoImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getAtributo()
     * @generated
     */
    EClass ATRIBUTO = eINSTANCE.getAtributo();

    /**
     * The meta object literal for the '<em><b>Atributo Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUTO__ATRIBUTO_NAME = eINSTANCE.getAtributo_AtributoName();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.FuncionSimplificadaImpl <em>Funcion Simplificada</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.FuncionSimplificadaImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getFuncionSimplificada()
     * @generated
     */
    EClass FUNCION_SIMPLIFICADA = eINSTANCE.getFuncionSimplificada();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCION_SIMPLIFICADA__NAME = eINSTANCE.getFuncionSimplificada_Name();

    /**
     * The meta object literal for the '<em><b>Atributo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION_SIMPLIFICADA__ATRIBUTO = eINSTANCE.getFuncionSimplificada_Atributo();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION_SIMPLIFICADA__THEN = eINSTANCE.getFuncionSimplificada_Then();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.EqualImpl <em>Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.EqualImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getEqual()
     * @generated
     */
    EClass EQUAL = eINSTANCE.getEqual();

    /**
     * The meta object literal for the '<em><b>N1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__N1 = eINSTANCE.getEqual_N1();

    /**
     * The meta object literal for the '<em><b>N2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL__N2 = eINSTANCE.getEqual_N2();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.IfImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__CONDITION = eINSTANCE.getIf_Condition();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__THEN = eINSTANCE.getIf_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__ELSE = eINSTANCE.getIf_Else();

    /**
     * The meta object literal for the '{@link edu.upb.lp.isc.compilacion.impl.BloqueImpl <em>Bloque</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.isc.compilacion.impl.BloqueImpl
     * @see edu.upb.lp.isc.compilacion.impl.CompilacionPackageImpl#getBloque()
     * @generated
     */
    EClass BLOQUE = eINSTANCE.getBloque();

  }

} //CompilacionPackage
