/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type </b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getDataType_()
 * @model
 * @generated
 */
public interface DataType_ extends Expr
{
} // DataType_
