/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaraciones</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getDeclaraciones()
 * @model
 * @generated
 */
public interface Declaraciones extends EObject
{
} // Declaraciones
