/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.Equal#getN1 <em>N1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.Equal#getN2 <em>N2</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getEqual()
 * @model
 * @generated
 */
public interface Equal extends Expr
{
  /**
   * Returns the value of the '<em><b>N1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N1</em>' containment reference.
   * @see #setN1(DataType_)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getEqual_N1()
   * @model containment="true"
   * @generated
   */
  DataType_ getN1();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.Equal#getN1 <em>N1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N1</em>' containment reference.
   * @see #getN1()
   * @generated
   */
  void setN1(DataType_ value);

  /**
   * Returns the value of the '<em><b>N2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N2</em>' containment reference.
   * @see #setN2(DataType_)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getEqual_N2()
   * @model containment="true"
   * @generated
   */
  DataType_ getN2();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.Equal#getN2 <em>N2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N2</em>' containment reference.
   * @see #getN2()
   * @generated
   */
  void setN2(DataType_ value);

} // Equal
