/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends Ejecucion, Simple
{
} // Expr
