/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funcion Simplificada</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getAtributo <em>Atributo</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getThen <em>Then</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getFuncionSimplificada()
 * @model
 * @generated
 */
public interface FuncionSimplificada extends Expr
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getFuncionSimplificada_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Atributo</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.compilacion.DataType_}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atributo</em>' containment reference list.
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getFuncionSimplificada_Atributo()
   * @model containment="true"
   * @generated
   */
  EList<DataType_> getAtributo();

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(Bloque)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getFuncionSimplificada_Then()
   * @model containment="true"
   * @generated
   */
  Bloque getThen();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.FuncionSimplificada#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(Bloque value);

} // FuncionSimplificada
