/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.If#getCondition <em>Condition</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.If#getThen <em>Then</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.If#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getIf()
 * @model
 * @generated
 */
public interface If extends Estructuras
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Equal)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getIf_Condition()
   * @model containment="true"
   * @generated
   */
  Equal getCondition();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.If#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Equal value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(Bloque)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getIf_Then()
   * @model containment="true"
   * @generated
   */
  Bloque getThen();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.If#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(Bloque value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(Bloque)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getIf_Else()
   * @model containment="true"
   * @generated
   */
  Bloque getElse();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.If#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(Bloque value);

} // If
