/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Is Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.IsDataType#getIsType <em>Is Type</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getIsDataType()
 * @model
 * @generated
 */
public interface IsDataType extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Type</em>' containment reference.
   * @see #setIsType(DataType_)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getIsDataType_IsType()
   * @model containment="true"
   * @generated
   */
  DataType_ getIsType();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.IsDataType#getIsType <em>Is Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Type</em>' containment reference.
   * @see #getIsType()
   * @generated
   */
  void setIsType(DataType_ value);

} // IsDataType
