/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.List#getTypeOfList <em>Type Of List</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getList()
 * @model
 * @generated
 */
public interface List extends DataType_, LargoLista
{
  /**
   * Returns the value of the '<em><b>Type Of List</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.compilacion.DataType_}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Of List</em>' containment reference list.
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getList_TypeOfList()
   * @model containment="true"
   * @generated
   */
  EList<DataType_> getTypeOfList();

} // List
