/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>My Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.MyBool#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getMyBool()
 * @model
 * @generated
 */
public interface MyBool extends DataType_
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Bool)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getMyBool_Value()
   * @model containment="true"
   * @generated
   */
  Bool getValue();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.MyBool#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Bool value);

} // MyBool
