/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>No Imprimible</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.NoImprimible#getVar <em>Var</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.NoImprimible#getFun <em>Fun</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getNoImprimible()
 * @model
 * @generated
 */
public interface NoImprimible extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(Variables)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getNoImprimible_Var()
   * @model
   * @generated
   */
  Variables getVar();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.NoImprimible#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Variables value);

  /**
   * Returns the value of the '<em><b>Fun</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fun</em>' reference.
   * @see #setFun(FuncionSimplificada)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getNoImprimible_Fun()
   * @model
   * @generated
   */
  FuncionSimplificada getFun();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.NoImprimible#getFun <em>Fun</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fun</em>' reference.
   * @see #getFun()
   * @generated
   */
  void setFun(FuncionSimplificada value);

} // NoImprimible
