/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Programa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.Programa#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.Programa#getDeclaraciones <em>Declaraciones</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.Programa#getEjecuciones <em>Ejecuciones</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getPrograma()
 * @model
 * @generated
 */
public interface Programa extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getPrograma_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.upb.lp.isc.compilacion.Programa#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Declaraciones</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.compilacion.Declaraciones}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaraciones</em>' containment reference list.
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getPrograma_Declaraciones()
   * @model containment="true"
   * @generated
   */
  EList<Declaraciones> getDeclaraciones();

  /**
   * Returns the value of the '<em><b>Ejecuciones</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.isc.compilacion.Ejecucion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ejecuciones</em>' containment reference list.
   * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getPrograma_Ejecuciones()
   * @model containment="true"
   * @generated
   */
  EList<Ejecucion> getEjecuciones();

} // Programa
