/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.isc.compilacion.CompilacionPackage#getSimple()
 * @model
 * @generated
 */
public interface Simple extends Declaraciones, Bloque
{
} // Simple
