/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.ui;

import com.google.inject.Injector;
import compilacion.ui.internal.CompilacionActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CompilacionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CompilacionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CompilacionActivator activator = CompilacionActivator.getInstance();
		return activator != null ? activator.getInjector(CompilacionActivator.EDU_UPB_LP_ISC_COMPILACION) : null;
	}

}
