/*
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CompilacionUiModule extends AbstractCompilacionUiModule {

	public CompilacionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
