/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion.impl;

import edu.upb.lp.isc.compilacion.CompilacionPackage;
import edu.upb.lp.isc.compilacion.DataType_;
import edu.upb.lp.isc.compilacion.Equal;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Equal</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.impl.EqualImpl#getN1 <em>N1</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.impl.EqualImpl#getN2 <em>N2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EqualImpl extends ExprImpl implements Equal
{
  /**
   * The cached value of the '{@link #getN1() <em>N1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN1()
   * @generated
   * @ordered
   */
  protected DataType_ n1;

  /**
   * The cached value of the '{@link #getN2() <em>N2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getN2()
   * @generated
   * @ordered
   */
  protected DataType_ n2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EqualImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CompilacionPackage.Literals.EQUAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataType_ getN1()
  {
    return n1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN1(DataType_ newN1, NotificationChain msgs)
  {
    DataType_ oldN1 = n1;
    n1 = newN1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CompilacionPackage.EQUAL__N1, oldN1, newN1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN1(DataType_ newN1)
  {
    if (newN1 != n1)
    {
      NotificationChain msgs = null;
      if (n1 != null)
        msgs = ((InternalEObject)n1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CompilacionPackage.EQUAL__N1, null, msgs);
      if (newN1 != null)
        msgs = ((InternalEObject)newN1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CompilacionPackage.EQUAL__N1, null, msgs);
      msgs = basicSetN1(newN1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CompilacionPackage.EQUAL__N1, newN1, newN1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataType_ getN2()
  {
    return n2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetN2(DataType_ newN2, NotificationChain msgs)
  {
    DataType_ oldN2 = n2;
    n2 = newN2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CompilacionPackage.EQUAL__N2, oldN2, newN2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setN2(DataType_ newN2)
  {
    if (newN2 != n2)
    {
      NotificationChain msgs = null;
      if (n2 != null)
        msgs = ((InternalEObject)n2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CompilacionPackage.EQUAL__N2, null, msgs);
      if (newN2 != null)
        msgs = ((InternalEObject)newN2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CompilacionPackage.EQUAL__N2, null, msgs);
      msgs = basicSetN2(newN2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CompilacionPackage.EQUAL__N2, newN2, newN2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompilacionPackage.EQUAL__N1:
        return basicSetN1(null, msgs);
      case CompilacionPackage.EQUAL__N2:
        return basicSetN2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CompilacionPackage.EQUAL__N1:
        return getN1();
      case CompilacionPackage.EQUAL__N2:
        return getN2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CompilacionPackage.EQUAL__N1:
        setN1((DataType_)newValue);
        return;
      case CompilacionPackage.EQUAL__N2:
        setN2((DataType_)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CompilacionPackage.EQUAL__N1:
        setN1((DataType_)null);
        return;
      case CompilacionPackage.EQUAL__N2:
        setN2((DataType_)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CompilacionPackage.EQUAL__N1:
        return n1 != null;
      case CompilacionPackage.EQUAL__N2:
        return n2 != null;
    }
    return super.eIsSet(featureID);
  }

} //EqualImpl
