/**
 * generated by Xtext 2.25.0
 */
package edu.upb.lp.isc.compilacion.impl;

import edu.upb.lp.isc.compilacion.CompilacionPackage;
import edu.upb.lp.isc.compilacion.Declaraciones;
import edu.upb.lp.isc.compilacion.Ejecucion;
import edu.upb.lp.isc.compilacion.Programa;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Programa</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.isc.compilacion.impl.ProgramaImpl#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.impl.ProgramaImpl#getDeclaraciones <em>Declaraciones</em>}</li>
 *   <li>{@link edu.upb.lp.isc.compilacion.impl.ProgramaImpl#getEjecuciones <em>Ejecuciones</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramaImpl extends MinimalEObjectImpl.Container implements Programa
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDeclaraciones() <em>Declaraciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclaraciones()
   * @generated
   * @ordered
   */
  protected EList<Declaraciones> declaraciones;

  /**
   * The cached value of the '{@link #getEjecuciones() <em>Ejecuciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEjecuciones()
   * @generated
   * @ordered
   */
  protected EList<Ejecucion> ejecuciones;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CompilacionPackage.Literals.PROGRAMA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CompilacionPackage.PROGRAMA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Declaraciones> getDeclaraciones()
  {
    if (declaraciones == null)
    {
      declaraciones = new EObjectContainmentEList<Declaraciones>(Declaraciones.class, this, CompilacionPackage.PROGRAMA__DECLARACIONES);
    }
    return declaraciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Ejecucion> getEjecuciones()
  {
    if (ejecuciones == null)
    {
      ejecuciones = new EObjectContainmentEList<Ejecucion>(Ejecucion.class, this, CompilacionPackage.PROGRAMA__EJECUCIONES);
    }
    return ejecuciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompilacionPackage.PROGRAMA__DECLARACIONES:
        return ((InternalEList<?>)getDeclaraciones()).basicRemove(otherEnd, msgs);
      case CompilacionPackage.PROGRAMA__EJECUCIONES:
        return ((InternalEList<?>)getEjecuciones()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CompilacionPackage.PROGRAMA__NAME:
        return getName();
      case CompilacionPackage.PROGRAMA__DECLARACIONES:
        return getDeclaraciones();
      case CompilacionPackage.PROGRAMA__EJECUCIONES:
        return getEjecuciones();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CompilacionPackage.PROGRAMA__NAME:
        setName((String)newValue);
        return;
      case CompilacionPackage.PROGRAMA__DECLARACIONES:
        getDeclaraciones().clear();
        getDeclaraciones().addAll((Collection<? extends Declaraciones>)newValue);
        return;
      case CompilacionPackage.PROGRAMA__EJECUCIONES:
        getEjecuciones().clear();
        getEjecuciones().addAll((Collection<? extends Ejecucion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CompilacionPackage.PROGRAMA__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CompilacionPackage.PROGRAMA__DECLARACIONES:
        getDeclaraciones().clear();
        return;
      case CompilacionPackage.PROGRAMA__EJECUCIONES:
        getEjecuciones().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CompilacionPackage.PROGRAMA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CompilacionPackage.PROGRAMA__DECLARACIONES:
        return declaraciones != null && !declaraciones.isEmpty();
      case CompilacionPackage.PROGRAMA__EJECUCIONES:
        return ejecuciones != null && !ejecuciones.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ProgramaImpl
